version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: techChallenge
      MONGO_INITDB_ROOT_PASSWORD: fiap
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: techChallenge
      ME_CONFIG_MONGODB_ADMINPASSWORD: fiap
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: techChallenge
      ME_CONFIG_BASICAUTH_PASSWORD: fiap
    ports:
      - "8082:8081"
volumes:
  mongodata:
    driver: local
